language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
install:
  - mix local.rebar --force;
  - mix local.hex --force
  - mix deps.get
  - mix format --check-formatted
script:
  - mix test
  - mix test.integration
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
branches:
  only:
  - master
  - /\d{1,3}\.\d{1,3}\.\d{1,3}/
